version: '3.9'

networks:
 learnstream-net:
  driver: bridge


services:
  postgres:
    image: postgres:15
    container_name: postgres
    restart: always
    environment:
       POSTGRES_USER : postgres
       POSTGRES_PASSWORD : postgres
       POSTGRES_MULTIPLE_DATABASES : "authdb,userdb"
    ports:
      - "5432:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    networks:
      - learnstream-net

  mongo:
    image: mongo:6
    container_name: mongo
    restart : always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - learnstream-net
  redis:
    image: redis:7
    container_name: redis
    restart : always
    ports:
      - "6380:6379"
    networks:
      - learnstream-net
  zookeeper:
    image: confluentinc/cp-zookeeper:7.5.0
    container_name: zookeeper
    environment:
      ZOOKEEPER_CLIENT_PORT: 2181
    ports:
      - "2181:2181"
    networks:
      - learnstream-net

  broker:
    image: confluentinc/cp-kafka:7.5.0
    container_name: broker
    depends_on:
      - zookeeper
    ports:
      - "29092:29092"
      - "9092:9092"
    environment:
      KAFKA_BROKER_ID: 1
      KAFKA_ZOOKEEPER_CONNECT: zookeeper:2181

      KAFKA_LISTENERS: INTERNAL://0.0.0.0:29092,EXTERNAL://0.0.0.0:9092
      KAFKA_ADVERTISED_LISTENERS: INTERNAL://broker:29092,EXTERNAL://localhost:9092
      KAFKA_LISTENER_SECURITY_PROTOCOL_MAP: INTERNAL:PLAINTEXT,EXTERNAL:PLAINTEXT
      KAFKA_INTER_BROKER_LISTENER_NAME: INTERNAL

      KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_REPLICATION_FACTOR: 1
      KAFKA_TRANSACTION_STATE_LOG_MIN_ISR: 1
      KAFKA_GROUP_INITIAL_REBALANCE_DELAY_MS: 0

      ALLOW_PLAINTEXT_LISTENER: "yes"
    networks:
      - learnstream-net

  auth:
    build: ./services/auth
    container_name: auth
    depends_on:
      - postgres
      - broker
    env_file:
      - ./services/auth/.env
    ports:
      - "4001:4001"
    networks:
      - learnstream-net
  user:
    build: ./services/user
    container_name: user
    depends_on:
      - postgres
      - broker
    env_file:
      - ./services/user/.env
    ports:
      - "4002:4002"
    networks:
      - learnstream-net

  activity:
    build: ./services/activity
    container_name: activity
    depends_on:
      - mongo
      - broker
    env_file:
      - ./services/activity/.env
    ports:
      - "4005:4005"
    networks:
      - learnstream-net
    
  notification:
    build: ./services/notification
    container_name: notification
    depends_on:
      - postgres
    env_file:
      - ./services/notification/.env
    ports:
      - "4006:4006"
    networks:
      - learnstream-net

  courses:
    build: ./services/course
    container_name: courses
    depends_on:
      - postgres
    env_file:
      - ./services/course/.env
    ports:
      - "4003:4003"
    networks:
      - learnstream-net

  content:
    build: ./services/content
    container_name: content
    depends_on:
      - postgres
    env_file:
      - ./services/content/.env
    ports:
      - "4004:4004"
    networks:
      - learnstream-net

  gateway:
    build: ./services/gateway
    container_name: gateway
    environment:
      - NODE_ENV=development
      - ACCESS_TOKEN_SECRET=supersecretkey
    depends_on:
      - auth
      - user
      - activity
      - redis
    env_file:
      - ./services/gateway/.env
    ports:
      - "3001:3001"
    networks:
      - learnstream-net


volumes:
  postgres_data:
  mongo_data:

